# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(help_text='服务器ip地址', verbose_name='服务器ip地址')),
                ('name', models.CharField(default='', help_text='服务器名称', max_length=30, verbose_name='服务器名称')),
                ('desc', models.CharField(default='', help_text='服务器详细信息', max_length=255, verbose_name='服务器详细信息')),
                ('ssh_name', models.CharField(help_text='ssh登录账户名', max_length=50, verbose_name='ssh登录账户名')),
                ('ssh_password', models.CharField(help_text='ssh登录密码', max_length=50, verbose_name='ssh登录密码')),
                ('ssh_port', models.CharField(default='22', help_text='ssh端口', max_length=6, verbose_name='ssh端口')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('last_scan_time', models.DateTimeField(blank=True, help_text='上次扫描时间', null=True, verbose_name='上次扫描时间')),
                ('server_is_active', models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, help_text='服务器是否存活', verbose_name='服务器是否存活')),
                ('ssh_is_active', models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, help_text='ssh端口是否存活', verbose_name='ssh端口是否存活')),
                ('ssh_error_msg', models.CharField(blank=True, default='', help_text='ssh连接失败原因', max_length=200, null=True, verbose_name='ssh连接失败原因')),
            ],
            options={
                'verbose_name': '服务器信息',
                'verbose_name_plural': '服务器信息',
            },
        ),
    ]
