# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(help_text='服务器ip地址', verbose_name='服务器ip地址')),
                ('name', models.CharField(default='', help_text='服务器名称', max_length=30, verbose_name='服务器名称')),
                ('desc', models.CharField(default='', help_text='服务器详细信息', max_length=255, verbose_name='服务器详细信息')),
                ('ssh_name', models.CharField(help_text='ssh登录账户名', max_length=50, verbose_name='ssh登录账户名')),
                ('ssh_password', models.CharField(help_text='ssh登录密码', max_length=50, verbose_name='ssh登录密码')),
            ],
            options={
                'verbose_name': '服务器信息',
                'verbose_name_plural': '服务器信息',
            },
        ),
    ]
