# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetail',
            name='ssh_port',
            field=models.CharField(default='22', help_text='ssh端口', max_length=6, verbose_name='ssh端口'),
        ),
    ]
