# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_used', models.CharField(help_text='内存使用空间大小', max_length=15, verbose_name='内存使用空间大小')),
                ('memory_free', models.CharField(help_text='内存空置空间大小', max_length=15, verbose_name='内存空置空间大小')),
                ('cpu_per', models.CharField(help_text='cpu使用率', max_length=5, verbose_name='cpu使用率')),
                ('last_update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('server', models.OneToOneField(help_text='对应服务器', on_delete=django.db.models.deletion.CASCADE, to='server.ServerDetail', verbose_name='对应服务器')),
            ],
            options={
                'verbose_name': '服务器硬件使用状况',
                'verbose_name_plural': '服务器硬件使用状况',
            },
        ),
    ]
