# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_serverstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
