# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20180410_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdetail',
            name='server_is_active',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, help_text='服务器是否存活', verbose_name='服务器是否存活'),
        ),
        migrations.AlterField(
            model_name='serverdetail',
            name='ssh_is_active',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, help_text='ssh端口是否存活', verbose_name='ssh端口是否存活'),
        ),
    ]
