# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20180419_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdetail',
            name='compute_house',
            field=models.ForeignKey(blank=True, help_text='所属机房', null=True, on_delete=django.db.models.deletion.CASCADE, to='server.ComputeHouse', verbose_name='所属机房'),
        ),
    ]
