# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_serverdetail_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdetail',
            name='add_time',
        ),
        migrations.AddField(
            model_name='serverdetail',
            name='is_active',
            field=models.BooleanField(default=False, help_text='是否存活', verbose_name='是否存活'),
        ),
    ]
