# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('server', '0008_auto_20180419_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdetail',
            name='ssh_error_msg',
        ),
        migrations.AddField(
            model_name='serverdetail',
            name='internal_ip',
            field=models.GenericIPAddressField(help_text='内网ip', null=True, verbose_name='内网ip'),
        ),
        migrations.AddField(
            model_name='serverdetail',
            name='server_kind',
            field=models.CharField(choices=[('1', 'linux'), ('2', 'windows'), ('3', '预留')], default='1', help_text='服务器系统', max_length=2, verbose_name='服务器系统'),
        ),
        migrations.AddField(
            model_name='serverdetail',
            name='server_status',
            field=models.CharField(choices=[('0', '回收'), ('1', '使用中'), ('2', '待使用')], default='1', help_text='服务器状态', max_length=2, verbose_name='服务器状态'),
        ),
        migrations.AddField(
            model_name='serverdetail',
            name='union_ip',
            field=models.GenericIPAddressField(help_text='联通ip', null=True, verbose_name='联通ip'),
        ),
        migrations.AlterField(
            model_name='serverdetail',
            name='ip',
            field=models.GenericIPAddressField(help_text='电信ip地址', verbose_name='电信ip地址)'),
        ),
        migrations.RemoveField(
            model_name='serverdetail',
            name='server_group',
        ),
        migrations.AddField(
            model_name='serverdetail',
            name='server_group',
            field=models.ForeignKey(blank=True, help_text='所属服务器组', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.SubProjectsServerGroup', verbose_name='所属服务器组'),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='server',
            field=models.OneToOneField(blank=True, help_text='对应服务器', on_delete=django.db.models.deletion.CASCADE, to='server.ServerDetail', verbose_name='对应服务器'),
        ),
    ]
