# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20180228_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetail',
            name='last_scan_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, help_text='上次扫描时间', verbose_name='上次扫描时间'),
        ),
        migrations.AlterField(
            model_name='serverdetail',
            name='is_active',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, help_text='是否存活', verbose_name='是否存活'),
        ),
    ]
