# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20180228_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdetail',
            name='last_scan_time',
            field=models.DateTimeField(help_text='上次扫描时间', null=True, verbose_name='上次扫描时间'),
        ),
    ]
