# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_serverdetail_last_scan_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetail',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
