# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_serverdetail_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdetail',
            name='last_scan_time',
            field=models.DateTimeField(blank=True, help_text='上次扫描时间', null=True, verbose_name='上次扫描时间'),
        ),
    ]
