# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_auto_20180228_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdetail',
            name='is_active',
        ),
        migrations.AddField(
            model_name='serverdetail',
            name='server_is_active',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, help_text='服务器是否存活', verbose_name='服务器是否存活'),
        ),
        migrations.AddField(
            model_name='serverdetail',
            name='ssh_is_active',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, help_text='ssh端口是否存活', verbose_name='ssh端口是否存活'),
        ),
    ]
