# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_auto_20180228_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetail',
            name='ssh_error_msg',
            field=models.CharField(blank=True, default='', help_text='ssh连接失败原因', max_length=200, null=True, verbose_name='ssh连接失败原因'),
        ),
    ]
