# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='项目组名称', max_length=50, unique=True, verbose_name='项目组名称')),
                ('desc', models.CharField(help_text='项目组描述', max_length=200, verbose_name='项目描述')),
                ('creator', models.ForeignKey(help_text='项目组创建者', on_delete=django.db.models.deletion.CASCADE, related_name='user_group_creator', to=settings.AUTH_USER_MODEL, verbose_name='项目组创建者')),
                ('manages', models.ManyToManyField(blank=True, help_text='项目管理员', related_name='user_group_managers', to=settings.AUTH_USER_MODEL, verbose_name='项目管理员')),
                ('members', models.ManyToManyField(blank=True, help_text='项目组成员', related_name='user_group_members', to=settings.AUTH_USER_MODEL, verbose_name='项目组成员')),
            ],
            options={
                'verbose_name': '项目组',
                'verbose_name_plural': '项目组',
            },
        ),
    ]
