# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=100, verbose_name='项目名称')),
                ('desc', models.CharField(help_text='项目描述', max_length=500, verbose_name='项目描述')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='项目添加时间', verbose_name='项目添加时间')),
                ('creator', models.ForeignKey(help_text='项目创建则', on_delete=django.db.models.deletion.CASCADE, related_name='projects_creator', to=settings.AUTH_USER_MODEL, verbose_name='项目创建者')),
                ('managers', models.ManyToManyField(help_text='项目管理者', related_name='projects_managers', to=settings.AUTH_USER_MODEL, verbose_name='项目管理者')),
                ('members', models.ManyToManyField(help_text='项目成员', related_name='projects_members', to=settings.AUTH_USER_MODEL, verbose_name='项目成员')),
            ],
            options={
                'verbose_name': '总项目',
                'verbose_name_plural': '总项目',
            },
        ),
        migrations.CreateModel(
            name='SubProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=100, verbose_name='项目名称')),
                ('desc', models.CharField(help_text='项目描述', max_length=500, verbose_name='项目描述')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='项目添加时间', verbose_name='项目添加时间')),
                ('creator', models.ForeignKey(help_text='项目创建则', on_delete=django.db.models.deletion.CASCADE, related_name='sub_projects_creator', to=settings.AUTH_USER_MODEL, verbose_name='项目创建者')),
            ],
            options={
                'verbose_name': '子项目',
                'verbose_name_plural': '子项目',
            },
        ),
        migrations.CreateModel(
            name='SubProjectsKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类型名称', max_length=20, verbose_name='类型名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='项目添加时间', verbose_name='项目添加时间')),
                ('desc', models.CharField(help_text='类型描述', max_length=500, verbose_name='类型描述')),
            ],
            options={
                'verbose_name': '子项目类型',
                'verbose_name_plural': '子项目类型',
            },
        ),
        migrations.CreateModel(
            name='SubProjectsServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=100, verbose_name='项目名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('members', models.ManyToManyField(help_text='项目成员', to=settings.AUTH_USER_MODEL, verbose_name='项目成员')),
                ('sub_project', models.ForeignKey(help_text='所属子项目', on_delete=django.db.models.deletion.CASCADE, to='project.SubProjects', verbose_name='所属子项目')),
            ],
            options={
                'verbose_name': '子项目服务器组',
                'verbose_name_plural': '子项目服务器组',
            },
        ),
        migrations.AddField(
            model_name='subprojects',
            name='kind',
            field=models.OneToOneField(help_text='子项目类型', on_delete=django.db.models.deletion.CASCADE, to='project.SubProjectsKind', verbose_name='子项目类型'),
        ),
        migrations.AddField(
            model_name='subprojects',
            name='managers',
            field=models.ManyToManyField(help_text='项目管理者', to=settings.AUTH_USER_MODEL, verbose_name='项目管理者'),
        ),
        migrations.AddField(
            model_name='subprojects',
            name='project',
            field=models.ForeignKey(help_text='所属总项目', on_delete=django.db.models.deletion.CASCADE, to='project.Projects', verbose_name='所属总项目'),
        ),
    ]
