# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0004_auto_20180410_1407'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServerCommandLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(help_text='用户执行的命令', max_length=150, verbose_name='用户执行的命令')),
                ('command_res', models.TextField(help_text='执行命令返回数据', verbose_name='执行命令返回数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('server', models.ForeignKey(help_text='操作服务器', on_delete=django.db.models.deletion.CASCADE, to='server.ServerDetail', verbose_name='操作服务器')),
                ('user', models.ForeignKey(help_text='操作用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name_plural': '用户在服务器上面执行命令行',
                'verbose_name': '用户在服务器上面执行命令行',
            },
        ),
    ]
